---
# vars file for Elasticsearch

elasticsearch_container_name: "Elasticsearch"
elasticsearch_container_description: "Elasticsearch in Docker container"
elasticsearch_container_cmd: ""
elasticsearch_version: 5.5.0
elasticsearch_container_image: "docker.elastic.co/elasticsearch/elasticsearch"
elasticsearch_full_image: "{{ elasticsearch_container_image }}:{{ elasticsearch_version }}"
elasticsearch_container_ports:
 - "9200:9200"
 - "9300:9300"
elasticsearch_container_volumes:
 - "{{ elasticsearch_conf_dir }}:/usr/share/elasticsearch/config"
 - "{{ elasticsearch_data_dir }}:/usr/share/elasticsearch/data"
elasticsearch_container_extra_options: 
 - --net host 
 - "--ulimit nofile=65536:65536"
elasticsearch_env_variables:
 - '"ES_JAVA_OPTS=-Xms2G -Xmx2G"'
 - Dlog4j2.disable.jmx=true 
 - transport.host=127.0.0.1 
 - http.host=0.0.0.0 
 - bootstrap_memory_lock=true
elasticsearch_source_conf_dir: conf/
elasticsearch_conf_dir: /opt/elasticsearch/conf/
elasticsearch_data_dir: /opt/elasticsearch/data/
elasticsearch_scripts_dir: /opt/elasticsearch/conf/scripts