docker_elasticsearch_name: elasticsearch_1
docker_elasticsearch_image: my-es-image
#docker_elasticsearch_image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
docker_elasticsearch_source_conf_dir: conf/
docker_elasticsearch_conf_dir: /opt/elasticsearch/conf/
docker_elasticsearch_data_dir: /opt/elasticsearch/data/
docker_elasticsearch_env:
  ES_JAVA_OPTS: "-Xms2G -Xmx2G"
  Dlog4j2.disable.jmx: true
  transport.host: 127.0.0.1
  http.host: 0.0.0.0
  bootstrap_memory_lock: true
docker_elasticsearch_hostname: "{{ ansible_nodename }}"
docker_elasticsearch_net: bridge
docker_elasticsearch_expose:
  - 9200
  - 9300
docker_elasticsearch_ports:
  - 9200:9200
  - 9300:9300
docker_elasticsearch_volumes:
  - "{{ docker_elasticsearch_conf_dir }}:/usr/share/elasticsearch/config"
  - "{{ docker_elasticsearch_data_dir }}:/usr/share/elasticsearch/data"
docker_elasticsearch_memory_limit: 0