- name: Ensure docker elasticsearch directories exist
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_elasticsearch_conf_dir }}"
    - "{{ docker_elasticsearch_data_dir }}"

- name: Copy docker elasticsearch configuration settings
  copy:
    src: "{{ docker_elasticsearch_source_conf_dir }}"
    dest: "{{ docker_elasticsearch_conf_dir }}"
    mode: 0644
    
- name: Change vm.max_map_count to 262144
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

#- name: Restart docker elasticsearch container
#  become: yes
#  shell: "docker restart {{ docker_elasticsearch_name }}"

- name: Run docker elasticsearch container
  docker:
    env: "{{ docker_elasticsearch_env }}"
    expose: "{{ docker_elasticsearch_expose }}"
    hostname: "{{ docker_elasticsearch_hostname }}"
    image: "{{ docker_elasticsearch_image }}"
    name: "{{ docker_elasticsearch_name }}"
    net: "{{ docker_elasticsearch_net }}"
    ports: "{{ docker_elasticsearch_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    ulimits: 65536:65536
    volumes: "{{ docker_elasticsearch_volumes }}"
