- name: Ensure docker elasticsearch directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ elasticsearch_conf_dir }}"
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_scripts_dir }}"

- name: Copy docker elasticsearch configuration settings
  copy:
    src: "{{ elasticsearch_source_conf_dir }}"
    dest: "{{ elasticsearch_conf_dir }}"
    mode: 0644
  notify: restart elasticsearch
        
- name: create elasticsearch service file
  template:
    src: "templates/elasticsearch.service.j2"
    dest: "/etc/systemd/system/elasticsearch.service"
  notify: restart elasticsearch
