- name: Ensure docker fluentd directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ fluentd_conf_dir }}"
    - "{{ fluentd_data_dir }}"

- name: Copy docker fluentd configuration settings
  copy:
    src: "{{ fluentd_source_conf_dir }}"
    dest: "{{ fluentd_conf_dir }}"
    mode: 0644
  notify: restart fluentd
    
- name: create fluentd service file
  template:
    src: "templates/fluentd.service.j2"
    dest: "/etc/systemd/system/fluentd.service"
  notify: restart fluentd