# tasks file for docker-systemd
---
- name: create {{ container_service_name }} service file
  template:
    dest: "/etc/systemd/system/{{ container_service_name }}"
    src: "templates/systemd-container.service.j2"
  register: service_config

- name: Load image from archive
  docker_image:
    name: "{{ container_image }}"
    #tag: "{{ tag }}"
    load_path: "{{ path }}"
  when: dockerhub == false

- name: reload {{ container_service_name }} daemon
  shell: systemctl daemon-reload
  when: service_config.changed

- name: restart {{ container_service_name }} service
  service:
    name: "{{ container_service_name }}"
    state: restarted
  when: service_config.changed

- name: enable {{ container_service_name }} service
  service:
    name: "{{ container_service_name }}"
    state: started
    enabled: yes