- name: Ensure docker kibana directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ kibana_conf_dir }}"

- name: Copy docker kibana configuration settings
  copy:
    src: "{{ kibana_source_conf_dir }}"
    dest: "{{ kibana_conf_dir }}"
    mode: 0644
    notify: restart kibana

- name: create kibana service file
  template:
    src: "templates/kibana.service.j2"
    dest: "/etc/systemd/system/kibana.service"
  notify: restart kibana